---

- name:  Copy PHP App directory to the remote servers
  synchronize:
    src: /var/lib/jenkins/workspace/test-php/
    dest: /var/www/html/htmly/laravel-permissions
  notify:
    - reload nginx

- name : set app dir permissions
  file:
    dest: /var/www/html/htmly/laravel-permissions
    owner: www-data
    group: www-data
    recurse: yes

- name: Composer install Deps
  composer:
    command: install
    working_dir: /var/www/html/htmly/laravel-permissions

- name: Run artisan migrate
  shell: sudo php /var/www/html/htmly/laravel-permissions/artisan migrate --path /var/www/html/htmly/laravel-permissions/database/migrations --force 
