---

- name:  Copy PHP App directory to the remote servers
  copy:
    src: /var/lib/jenkins/workspace/test-php/
    dest: /var/www/html/htmly/laravel-permissions
    owner: www-data
    group: www-data
    sudo: yes
    register: copyPHPapp


- name: Composer install Deps
  composer:
    command: install
    working_dir: /var/www/html/htmly/laravel-permissions
    register: depsInstall
    when: copyPHPapp is success
    sudo: yes

- name: Run artisan migrate
  shell: php /var/www/html/htmly/laravel-permissions/artisan migrate --path /var/www/html/htmly/laravel-permissions/database/migrations
  sudo: yes
  when: depsInstall is success
