---
- name: Install MySQL packages
  apt:
    name:
      - mysql-server
      - mysql-client
      - python-mysqldb
    state: present
    update_cache: yes


- name: Ensure that MySQL is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set the db root password
  debconf:
    name: mysql-server
    question: mysql-server/root_password
    value: "{{ root_password}}"
    vtype: password

- name: Confirm the db root password
  debconf:
    name: mysql-server
    question: mysql-server/root_password_again
    value: "{{ root_password}}"
    vtype: password

- name: Allow connections from remote hosts
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: 'bind-address\s*='
    line: 'bind-address = *'
  notify: restart mysql


- name: Create a database for Laravel
  mysql_db:
    db: phpdb
    state: present
    login_user: root
    login_password: "{{ root_password}}"
