---

- name: install MySQL packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items: "{{ mysql_packages }}"

- name: root database password
  debconf:
    name: mysql-server
    question: mysql-server/root_password
    value: wahba
    vtype: password

- name: Confirm root database password
  debconf:
    name: mysql-server
    question: mysql-server/root_password_again
    value: wahba
    vtype: password

  notify:
    - restart MySQL
